// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package go_challenge

import (
	"time"
)

type User struct {
	UserName          string
	HashedPassword    string
	FullName          string
	Email             string
	PasswordChangedAt time.Time
	CreatedAt         time.Time
}
